# Generated by Django 2.0.7 on 2018-07-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('regiao', models.CharField(max_length=20)),
                ('CEP', models.CharField(max_length=9)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descricao', models.CharField(max_length=200)),
                ('foto', models.ImageField(max_length=120, upload_to=None)),
            ],
        ),
    ]
