# Generated by Django 2.0.7 on 2018-07-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oimovelcerto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Foto'),
        ),
    ]
