# Generated by Django 2.0.7 on 2018-07-07 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oimovelcerto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cadastro',
        ),
    ]
