# Generated by Django 2.0.7 on 2018-07-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oimovelcerto', '0002_delete_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Titulo')),
                ('region', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=9)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
