# Generated by Django 2.0.7 on 2018-07-08 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oimovelcerto', '0003_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/%Y/%m/%d', verbose_name='Foto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='region',
            field=models.CharField(max_length=20, verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='zipcode',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
