# Generated by Django 2.0.7 on 2018-07-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oimovelcerto', '0004_auto_20180710_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='pictures',
        ),
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Foto'),
        ),
    ]
