# Generated by Django 2.0.7 on 2018-07-08 19:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oimovelcerto', '0005_auto_20180708_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='media/', verbose_name='Foto'),
        ),
    ]
