# Generated by Django 2.0.7 on 2018-07-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oimovelcerto', '0007_auto_20180708_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='search',
            name='zip_code',
            field=models.ManyToManyField(related_name='_search_zip_code_+', to='oimovelcerto.Search'),
        ),
    ]
