# Generated by Django 2.0.7 on 2018-07-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oimovelcerto', '0008_auto_20180708_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='zip_code',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
