# Generated by Django 2.0.7 on 2018-07-10 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oimovelcerto', '0009_auto_20180709_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='photo',
            new_name='image',
        ),
    ]
