# Generated by Django 2.0.7 on 2018-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oimovelcerto', '0010_auto_20180709_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Foto'),
        ),
    ]
