# Generated by Django 2.0.7 on 2018-07-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oimovelcerto', '0017_auto_20180710_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Foto'),
        ),
    ]
